FROM php:7.3-cli

# cp library
COPY libssh2.so* /usr/local/lib/

# add ssh2.so
COPY ssh2.so /usr/local/lib/php/extensions/no-debug-non-zts-20180731/ssh2.so

# cp test script and SSH keys
COPY sftp.php /app/sftp.php
COPY id_rsa /app/id_rsa
COPY id_rsa.pub /app/id_rsa.pub
RUN chmod 600 /app/id_rsa /app/id_rsa.pub

# Set extension & library path
ENV LD_LIBRARY_PATH=/usr/local/lib
RUN echo "extension=ssh2.so" > /usr/local/etc/php/conf.d/20-ssh2.ini

WORKDIR /app
CMD ["php", "sftp.php"]
